
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017 # ?? DB??
  batch:
    job:
      enabled: false # ?????? ??? ??? ?? ??? ???? ?? ??

# Movie Open Api ??
movie:
  openApi:
    trending:
      uri: https://api.themoviedb.org/3	# Default ?? ??
    apiKey : c4b71210409eb4dc48ed9f2138569b3b# API?